# Site settings
title: 朱俊杰的博客
SEOTitle: 朱俊杰的博客
header-img: img/post-bg-desk.jpg
email: 814460286@qq.com
description: "Every failure is leading towards success."
keyword: "朱俊杰的博客, java, python,js,web"
url: "http://jixiexuezhe.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/jixiexuezhe/jixiexuezhe.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "伟大的人物都在改变世界！"
sidebar-avatar: /img/avatar_m.jpg     # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     35rencai
zhihu_username:     35rencai
github_username:    35rencai
facebook_username:  35rencai
jianshu_username:   35rencai
#twitter_username:   35rencai




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: 35sui

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  repo: 35sui.github.io    #仓库名称
  owner: 35sui    #github用户名
  admin: 35sui
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: 35rencai.club               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "逗逼网，专业表情包",
        href: "http://bee-ji.com"
    },{
        title: "Google",
        href: "https://www.google.com/search?q=google&rlz=1C1GCEU_zh-CNSG830SG830&oq=g&aqs=chrome.4.69i60l2j69i59j69i60j0l2.1681j0j4&sourceid=chrome&ie=UTF-8"
    },{
        title: "spring core",
        href: "https://docs.spring.io/spring-framework/docs/5.1.3.RELEASE/spring-framework-reference/"
    },{
        title: "spring doc",
        href: "https://docs.spring.io/spring-framework/docs/5.1.3.RELEASE/"
    },{
        title: "菜鸟教程",
        href: "http://www.runoob.com/"
    },{
        title: "spring-boot docs",
        href: "https://docs.spring.io/spring-boot/docs/"
    },{
        title: "spring框架jar下载",
        href: "http://repo.spring.io/release/org/springframework/spring/"
    },{
        title: "Greenwich.RELEASE",
        href: "http://cloud.spring.io/spring-cloud-static/Greenwich.RELEASE/multi/multi_spring-cloud.html"
    },{
        title: "Finchley.SR1",
        href: "http://cloud.spring.io/spring-cloud-static/Finchley.SR1/multi/multi_spring-cloud.html"
    }
]
